name: "Deploy"

on:
  workflow_dispatch
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.15.2"
          spago: "latest"
      
      - name: "Build"
        run: spago bundle-app -t static/index.js

      - uses: shimataro/ssh-key-action@v2
        with:
         key: ${{ secrets.GANDI_CALENDAR_PRIVATE_KEY }}
         name: "gandi_key"
         known_hosts: ${{ secrets.GANDI_CALENDAR_KNOWN_HOSTS }}

      - name: "Deploy"
        run: |
          scp -i ~/.ssh/gandi_key static $USERNAME@$HOST:/var/calendar-halogen/static
